name: Build

on:
  push:
    paths:
      - 'Source/**'
      - '\.gitignore'

jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
            8.0.x
            9.0.x

    - name: Restore dependencies
      run: dotnet restore Source/MuniNet.sln
          
    - name: Build
      run: dotnet build --no-restore Source/MuniNet.sln /p:Configuration=Release /p:Platform="Any CPU"
      
    - name: Run all tests
      working-directory: Source
      run: dotnet test --configuration Release --logger trx --results-directory "XunitTestReports" --filter "Category=CI"
 
    - name: Run Redis tests
      working-directory: Source
      run: |
        cd Tests/Dockers/Redis && docker compose up -d
        dotnet test --configuration Release --logger trx --results-directory "XunitTestReports" --filter "Category=RedisIntegration"
        cd Tests/Dockers/Redis && docker compose down
